version: "3"
services:
  admin:
    image: wordpress:php8.0
    container_name: admin_wp
    depends_on:
      - admindb
    volumes:
      - wordpress_data:/var/www/html
      - "./plugins/premia-admin:/var/www/html/wp-content/plugins/premia-admin"
      - "./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini"
    restart: always
    environment:
      WORDPRESS_DB_HOST: admindb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_DEBUG_LOG: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wp.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.wp.entrypoints=websecure"
      - "traefik.http.routers.wp.tls.certresolver=myresolver"
  admindb:
    image: mysql:5.7
    container_name: admin_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
volumes:
  db_data: {}
  wordpress_data: {}

networks:
  default:
    external:
      name: swarm